# Copiar la imagen del jdk 1.8
FROM openjdk:8-jdk-alpine

VOLUME /tmp

# Puerto de salida para la ejecución
EXPOSE 8080

# Ejecucción de la aplicación con el comando java -jar.
ARG JAR_FILE=asedinfo-controlador.war
ADD ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]