package ec.gob.educacion.modelo.catalogo;
// default package

// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * cat_producto generated by hbm2java
 */
@Entity
@Table(name = "cat_producto")
public class Producto implements java.io.Serializable {
	private static final long serialVersionUID = -8622196233866959952L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false, precision = 10, scale = 0)
	private Long codigo;

	@Column(name = "cod_marca")
	private Long codMarca;

	@Column(name = "cod_unidad")
	private Long codUnidad;

	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "precio_compra")
	private float precioCompra;
	
	@Column(name = "precio_costo")
	private float precioCosto;
	
	@Column(name = "precio_mayoreo")
	private float precioMayoreo;
	
	@Column(name = "precio_minoreo")
	private float precioMinoreo;
	
	@Column(name = "aplica_iva")
	private int aplica;
	
	@Column(name = "num_existencia_actual")
	private int numExistenciaActual;
	
	@Column(name = "num_existencia_minima")
	private int numExistenciaMinima;

	@Column(name = "estado", nullable = false, length = 1)
	private String estado;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registra", length = 23)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss.SSS", locale = "es-EC", timezone = "America/Lima")
	private Date fechaRegistra;
	
	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "cod_modulo", nullable = false)
	private Modulo modulo;

	@Transient
	private Long codModulo;
	
	public Producto() {
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public Long getCodMarca() {
		return codMarca;
	}

	public void setCodMarca(Long codMarca) {
		this.codMarca = codMarca;
	}

	public Long getCodUnidad() {
		return codUnidad;
	}

	public void setCodUnidad(Long codUnidad) {
		this.codUnidad = codUnidad;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getPrecioCompra() {
		return precioCompra;
	}

	public void setPrecioCompra(float precioCompra) {
		this.precioCompra = precioCompra;
	}

	public float getPrecioCosto() {
		return precioCosto;
	}

	public void setPrecioCosto(float precioCosto) {
		this.precioCosto = precioCosto;
	}

	public float getPrecioMayoreo() {
		return precioMayoreo;
	}

	public void setPrecioMayoreo(float precioMayoreo) {
		this.precioMayoreo = precioMayoreo;
	}

	public float getPrecioMinoreo() {
		return precioMinoreo;
	}

	public void setPrecioMinoreo(float precioMinoreo) {
		this.precioMinoreo = precioMinoreo;
	}

	public int getAplica() {
		return aplica;
	}

	public void setAplica(int aplica) {
		this.aplica = aplica;
	}

	public int getNumExistenciaActual() {
		return numExistenciaActual;
	}

	public void setNumExistenciaActual(int numExistenciaActual) {
		this.numExistenciaActual = numExistenciaActual;
	}

	public int getNumExistenciaMinima() {
		return numExistenciaMinima;
	}

	public void setNumExistenciaMinima(int numExistenciaMinima) {
		this.numExistenciaMinima = numExistenciaMinima;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaRegistra() {
		return fechaRegistra;
	}

	public void setFechaRegistra(Date fechaRegistra) {
		this.fechaRegistra = fechaRegistra;
	}

	public Modulo getModulo() {
		return modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}
	
	public Long getCodModulo() {
		if (this.modulo != null) {
			codModulo = this.modulo.getCodigo();
		}
		return codModulo;
	}

	public void setCodModulo(Long codModulo) {
		this.codModulo = codModulo;
	}

}
