package ec.gob.educacion.modelo.seguridad;
// default package

// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ClaveUsuario generated by hbm2java
 */
@Entity
@Table(name = "seg_clave_usuario")
public class ClaveUsuario implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false, precision = 10, scale = 0)
	private Long codigo;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_usuario", unique = true, nullable = false)
	private Usuario usuario;

	@Column(name = "clave", nullable = false)
	private String clave;

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss.SSS", locale = "es-EC", timezone = "America/Lima")
	@Column(name = "fecha_inicio", nullable = false, length = 23)
	private Date fechaInicio;

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss.SSS", locale = "es-EC", timezone = "America/Lima")
	@Column(name = "fecha_fin", length = 23)
	private Date fechaFin;

	@Column(name = "ESTADO", nullable = false, length = 1)
	private String estado;

	@Column(name = "estado_fin_clave", length = 1)
	private String estadoFinClave;
	
	@Transient
	private Long codUsuario;

	public ClaveUsuario() {
	}

	public ClaveUsuario(Long codigo, Usuario usuario, String clave, Date fechaInicio, String estado) {
		this.codigo = codigo;
		this.usuario = usuario;
		this.clave = clave;
		this.fechaInicio = fechaInicio;
		this.estado = estado;
	}

	public ClaveUsuario(Long codigo, Usuario usuario, String clave, Date fechaInicio, Date fechaFin, String estado) {
		this.codigo = codigo;
		this.usuario = usuario;
		this.clave = clave;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estado = estado;
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getEstadoFinClave() {
		return estadoFinClave;
	}

	public void setEstadoFinClave(String estadoFinClave) {
		this.estadoFinClave = estadoFinClave;
	}

	public Long getCodUsuario() {
		if (this.usuario != null) {
			codUsuario = this.usuario.getCodigo();
		}
		return codUsuario;
	}

	public void setCodUsuario(Long codUsuario) {
		this.codUsuario = codUsuario;
	}
}
