package ec.gob.educacion.modelo.seguridad;
// default package

// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Recurso generated by hbm2java
 */
@Entity
@Table(name = "seg_recurso")
public class Recurso implements java.io.Serializable {
	private static final long serialVersionUID = 2666962894699612697L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false, precision = 10, scale = 0)
	private Long codigo;

	@Column(name = "nombre", nullable = false, length = 50)
	private String nombre;

	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "url", nullable = false, length = 150)
	private String url;
	
	@Column(name = "nivel", nullable = false, precision = 1, scale = 0)
	private Long nivel;
	
	@Column(name = "estado", nullable = false, length = 1)
	private String estado;

	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "codigo_padre", nullable = true)
	private Recurso padre;

	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "codigo_aplicacion", nullable = false)
	private Aplicacion aplicacion;

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "padre")
	private List<Recurso> recursos = new ArrayList<Recurso>(0);

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recurso")
	private List<RolAplicacionRecurso> rolAplicacionRecursos = new ArrayList<RolAplicacionRecurso>(0);
	
	@Transient
	private Long codigoPadre;
	@Transient
	private Long codigoAplicacion;
	@Transient
	private boolean asignado;

	public Recurso() {
	}

	public Recurso(Long codigo, Recurso padre, Aplicacion aplicacion, String nombre, String url, Long nivel,
			String estado) {
		this.codigo = codigo;
		this.padre = padre;
		this.aplicacion = aplicacion;
		this.nombre = nombre;
		this.url = url;
		this.nivel = nivel;
		this.estado = estado;
	}

	public Recurso(Long codigo, Recurso padre, Aplicacion aplicacion, String nombre, String descripcion, String url,
			Long nivel, String estado, List<Recurso> recursos, List<RolAplicacionRecurso> rolAplicacionRecursos) {
		this.codigo = codigo;
		this.padre = padre;
		this.aplicacion = aplicacion;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.url = url;
		this.nivel = nivel;
		this.estado = estado;
		this.recursos = recursos;
		this.rolAplicacionRecursos = rolAplicacionRecursos;
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public Recurso getPadre() {
		return this.padre;
	}

	public void setPadre(Recurso padre) {
		this.padre = padre;
	}

	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Long getNivel() {
		return this.nivel;
	}

	public void setNivel(Long nivel) {
		this.nivel = nivel;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public List<Recurso> getRecursos() {
		return this.recursos;
	}

	public void setRecursos(List<Recurso> recursos) {
		this.recursos = recursos;
	}

	public List<RolAplicacionRecurso> getRolAplicacionRecursos() {
		return this.rolAplicacionRecursos;
	}

	public void setRolAplicacionRecursos(List<RolAplicacionRecurso> rolAplicacionRecursos) {
		this.rolAplicacionRecursos = rolAplicacionRecursos;
	}

	public boolean isAsignado() {
		return asignado;
	}

	public void setAsignado(boolean asignado) {
		this.asignado = asignado;
	}

	public Long getCodigoPadre() {
		if (this.padre != null) {
			codigoPadre = this.padre.getCodigo();
		} 	
		return codigoPadre;
	}

	public void setCodigoPadre(Long codigoPadre) {
		this.codigoPadre = codigoPadre;
	}

	public Long getCodigoAplicacion() {
		if (this.aplicacion != null) {
			codigoAplicacion = this.aplicacion.getCodigo();
		}
		return codigoAplicacion;
	}

	public void setCodigoAplicacion(Long codigoAplicacion) {
		this.codigoAplicacion = codigoAplicacion;
	}

}
