package ec.gob.educacion.modelo.seguridad;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * RolAplicacionRecurso generated by hbm2java
 */
@Entity
@Table(name = "seg_rol_aplicacion_recurso")
public class RolAplicacionRecurso implements java.io.Serializable {
	private static final long serialVersionUID = -846385389407239324L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false, precision = 10, scale = 0)
	private Long codigo;

	@Column(name = "estado", length = 1)
	private String estado;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_recurso", nullable = false)
	private Recurso recurso;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_rol_aplicacion", nullable = false)
	private RolAplicacion rolAplicacion;

	@Transient
	private Long codigoRecurso;
	@Transient
	private Long codigoRolAplicacion;

	public RolAplicacionRecurso() {
	}

	public RolAplicacionRecurso(Long codigo, Recurso recurso, RolAplicacion rolAplicacion) {
		this.codigo = codigo;
		this.recurso = recurso;
		this.rolAplicacion = rolAplicacion;
	}

	public RolAplicacionRecurso(Long codigo, Recurso recurso, RolAplicacion rolAplicacion, String estado) {
		this.codigo = codigo;
		this.recurso = recurso;
		this.rolAplicacion = rolAplicacion;
		this.estado = estado;
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public Recurso getRecurso() {
		return this.recurso;
	}

	public void setRecurso(Recurso recurso) {
		this.recurso = recurso;
	}

	public RolAplicacion getRolAplicacion() {
		return this.rolAplicacion;
	}

	public void setRolAplicacion(RolAplicacion rolAplicacion) {
		this.rolAplicacion = rolAplicacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Long getCodigoRecurso() {
		if (this.recurso != null) {
			codigoRecurso = this.recurso.getCodigo(); 
		}
		return codigoRecurso;
	}

	public void setCodigoRecurso(Long codigoRecurso) {
		this.codigoRecurso = codigoRecurso;
	}

	public Long getCodigoRolAplicacion() {
		if (this.rolAplicacion != null) {
			codigoRolAplicacion = this.rolAplicacion.getCodigo(); 
		}
		return codigoRolAplicacion;
	}

	public void setCodigoRolAplicacion(Long codigoRolAplicacion) {
		this.codigoRolAplicacion = codigoRolAplicacion;
	}
}
