package ec.gob.educacion.modelo.seguridad;
// default package

// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

import ec.gob.educacion.venta.resources.Constantes;

/**
 * RolAplicacion generated by hbm2java
 */
@Entity
@Table(name = "seg_rol_aplicacion")
public class RolAplicacion implements java.io.Serializable {
	private static final long serialVersionUID = -7479265746227182404L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false, precision = 10, scale = 0)
	private Long codigo;

	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "cod_aplicacion", nullable = false)
	private Aplicacion aplicacion;

	@Column(name = "nombre", nullable = false, length = 50)
	private String nombreRol;
	
	@Column(name = "descripcion")
	private String descripcionRol;
	
	@Column(name = "estado", nullable = false, length = 1)
	private String estadoRol;

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss.SSS", locale = "es-EC", timezone = "America/Lima")
	@Column(name = "fec_inactivacion")
	private Date fecInactivacion;

	// Numerador para los roles de la aplicacion seguridades
	@Enumerated(EnumType.STRING)
	@Column(name = "enum_rol_seg", length = 24)
	private EnumRolSeguridad enumRolSeguridad;

	@Transient
	private Boolean asignadoAdministrador;
	@Transient
	private boolean estadoActivo;
	@Transient
	private boolean asignado;

	@JsonIgnore
	@OneToMany(mappedBy = "rolAplicacion")
	private List<RolAplicacionRecurso> rolAplicacionRecursos = new ArrayList<RolAplicacionRecurso>(0);

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rolAplicacion")
	private List<UsuarioRolAplicacion> usuarioRolAplicacions = new ArrayList<UsuarioRolAplicacion>(0);

	public enum EnumRolSeguridad {
		ADMINISTRADOR_GENERAL, ADMINISTRADOR_APLICACION, ADMINISTRADOR_OPERATIVO
	}
	
	@Transient
	private Long codAplicacion;
	
	public RolAplicacion() {
	}
	
	public RolAplicacion(Long codigo, Aplicacion aplicacion, String nombre) {
		this.codigo = codigo;
		this.aplicacion = aplicacion;
		this.nombreRol = nombre;
	}

	public RolAplicacion(Long codigo, Aplicacion aplicacion, String nombre, String descripcion, String estado,
			List<RolAplicacionRecurso> rolAplicacionRecursos, List<UsuarioRolAplicacion> usuarioRolAplicacions) {
		this.codigo = codigo;
		this.aplicacion = aplicacion;
		this.nombreRol = nombre;
		this.descripcionRol = descripcion;
		this.estadoRol = estado;
		this.rolAplicacionRecursos = rolAplicacionRecursos;
		this.usuarioRolAplicacions = usuarioRolAplicacions;
	}
	
	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	public String getNombreRol() {
		return this.nombreRol;
	}

	public void setNombreRol(String nombreRol) {
		this.nombreRol = nombreRol;
	}

	public String getDescripcionRol() {
		return this.descripcionRol;
	}

	public void setDescripcionRol(String descripcionRol) {
		this.descripcionRol = descripcionRol;
	}

	public List<RolAplicacionRecurso> getRolAplicacionRecursos() {
		return this.rolAplicacionRecursos;
	}

	public void setRolAplicacionRecursos(List<RolAplicacionRecurso> rolAplicacionRecursos) {
		this.rolAplicacionRecursos = rolAplicacionRecursos;
	}

	public List<UsuarioRolAplicacion> getUsuarioRolAplicacions() {
		return this.usuarioRolAplicacions;
	}

	public void setUsuarioRolAplicacions(List<UsuarioRolAplicacion> usuarioRolAplicacions) {
		this.usuarioRolAplicacions = usuarioRolAplicacions;
	}

	public String getEstadoRol() {
		return this.estadoRol;
	}

	public void setEstadoRol(String estadoRol) {
		this.estadoRol = estadoRol;
	}

	public boolean isEstadoActivo() {
		estadoRol = estadoRol == null ? " " : estadoRol; 
		return estadoRol.equals(Constantes.REGISTRO_ACTIVO);
	}

	public void setEstadoActivo(boolean estadoActivo) {
		this.estadoActivo = estadoActivo;
	}

	public boolean isAsignado() {
		return asignado;
	}

	public void setAsignado(boolean asignado) {
		this.asignado = asignado;
	}

	public EnumRolSeguridad getEnumRolSeguridad() {
		return enumRolSeguridad;
	}

	public void setEnumRolSeguridad(EnumRolSeguridad enumRolSeguridad) {
		this.enumRolSeguridad = enumRolSeguridad;
	}

	public Boolean getAsignadoAdministrador() {
		asignadoAdministrador = this.enumRolSeguridad == null ? false : true;
		return asignadoAdministrador;
	}

	public void setAsignadoAdministrador(Boolean asignadoAdministrador) {
		this.asignadoAdministrador = asignadoAdministrador;
	}

	public Date getFecInactivacion() {
		return fecInactivacion;
	}

	public void setFecInactivacion(Date fecInactivacion) {
		this.fecInactivacion = fecInactivacion;
	}

	public Long getCodAplicacion() {
		if (this.aplicacion != null) {
			codAplicacion = this.aplicacion.getCodigo();
		}
		return codAplicacion;
	}

	public void setCodAplicacion(Long codAplicacion) {
		this.codAplicacion = codAplicacion;
	}
}
