package ec.gob.educacion.modelo.seguridad;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Sede generated by hbm2java
 */
@Entity
@Table(name = "seg_sede")
public class Sede implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	private Long codigo;

	@Column(name = "nombre", nullable = false, length = 150)
	private String nombre;
	@Column(name = "descripcion")
	private String descripcion;
	@Column(name = "nemonico", length = 10)
	private String nemonico;
	@Column(name = "estado", nullable = false, length = 1)
	private String estado;
	
	@Transient
	private Long codigoSedeSuperior;

	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "sede_superior", nullable = true)
	private Sede sedeSuperior;

	public Sede() {
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getNemonico() {
		return this.nemonico;
	}

	public void setNemonico(String nemonico) {
		this.nemonico = nemonico;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Long getCodigoSedeSuperior() {
		if (this.sedeSuperior != null) {
			this.codigoSedeSuperior = this.sedeSuperior.getCodigo();
		}
		return this.codigoSedeSuperior;
	}

	public void setCodigoSedeSuperior(Long codigoSedeSuperior) {
		this.codigoSedeSuperior = codigoSedeSuperior;
	}

	public Sede getSedeSuperior() {
		return sedeSuperior;
	}

	public void setSedeSuperior(Sede sedeSuperior) {
		this.sedeSuperior = sedeSuperior;
	}
}
