package ec.gob.educacion.modelo.seguridad;
// default package

// Generated Nov 20, 2013 4:33:26 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AsignacionUsuarioAplicacion generated by hbm2java
 */
@Entity
@Table(name = "seg_usuario_aplicacion")
public class UsuarioAplicacion implements java.io.Serializable {
	private static final long serialVersionUID = 4276997527799111216L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false, precision = 10, scale = 0)
	private Long codigo;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_aplicacion", nullable = false)
	private Aplicacion aplicacion;

	@JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_usuario", nullable = false)
	private Usuario usuario;
	
	@Column(name = "estado", nullable = false, length = 1)
	private String estado;

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss.SSS", locale = "es-EC", timezone = "America/Lima")
	@Column(name = "fecha_asignacion", nullable = false)
	private Date fechaAsignacion;

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss.SSS", locale = "es-EC", timezone = "America/Lima")
	@Column(name = "fecha_finalizacion", nullable = true)
	private Date fechaFinalizacion;
	
	@Transient
	private Long codAplicacion;
	@Transient
	private Long codUsuario;

	public UsuarioAplicacion() {
	}

	public UsuarioAplicacion(Long codigo, Aplicacion aplicacion, Usuario usuario, Date fechaAsignacion) {
		this.codigo = codigo;
		this.aplicacion = aplicacion;
		this.usuario = usuario;
		this.fechaAsignacion = fechaAsignacion;
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFechaAsignacion() {
		return this.fechaAsignacion;
	}

	public void setFechaAsignacion(Date fechaAsignacion) {
		this.fechaAsignacion = fechaAsignacion;
	}

	public Date getFechaFinalizacion() {
		return this.fechaFinalizacion;
	}

	public void setFechaFinalizacion(Date fechaFinalizacion) {
		this.fechaFinalizacion = fechaFinalizacion;
	}

	public Long getCodUsuario() {
		if (this.usuario != null) {
			codUsuario = this.usuario.getCodigo();
		}
		return codUsuario;
	}

	public void setCodUsuario(Long codUsuario) {
		this.codUsuario = codUsuario;
	}

	public Long getCodAplicacion() {
		if (this.aplicacion != null) {
			codAplicacion = this.aplicacion.getCodigo();
		}
		return codAplicacion;
	}

	public void setCodAplicacion(Long codAplicacion) {
		this.codAplicacion = codAplicacion;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}
}
