package ec.gob.educacion.modelo.seguridad;
// default package

// Generated Oct 29, 2013 4:10:51 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import com.fasterxml.jackson.annotation.JsonIgnore;

import ec.gob.educacion.modelo.catalogo.Persona;
import ec.gob.educacion.modelo.seguridad.RolAplicacion.EnumRolSeguridad;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "seg_usuario")
public class Usuario implements java.io.Serializable {
	private static final long serialVersionUID = -8622196233866959952L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false, precision = 10, scale = 0)
	private Long codigo;
	
	@Column(name = "cambio_clave", nullable = false, length = 2)
	private String cambioClave;
	
	@Column(name = "actualizacion_datos", nullable = false, length = 2)
	private String actualizacionDatos;
	
	@Column(name = "token_cambio_clave", nullable = false, length = 255)
	private String tokenCambioClave;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_solicitud_clave", length = 23)
	private Date fechaSolicitudClave;
	
	@JsonIgnore
	@ManyToOne
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name = "cod_sede", nullable = false)
	private Sede sede;
	
	@JsonIgnore
	@ManyToOne
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name = "cod_persona", nullable = false)
	private Persona persona;
	
	@Column(name = "estado", nullable = false, length = 1)
	private String estado;

	// Numerador para los roles de la aplicacion seguridades
	@Enumerated(EnumType.STRING)
	@Column(name = "enum_rol_seg", length = 24)
	private EnumRolSeguridad enumRolSeguridad;

	@Column(name = "con_asignacion")
	private Boolean conAsignacion;

	@Column(name = "est_inactivar_roles", length = 1)
	private String estInactivarRoles;

	@Column(name = "est_activar_roles", length = 1)
	private String estActivarRoles;
	
	@Transient
	private String claveGenerada;
	@Transient
	private boolean esAdminAplicacion;
	@Transient
	private boolean esAdminOperativo;
	@Transient
	private String solicitado;
	@Transient
	private String tipoCreacionUsuario;
	@Transient
	private boolean esAsignacionOperativo;
	@Transient
	private boolean esSuperAdministrador;
	@Transient
	private String tipoUsuario;
	@Transient
	private Long codSede;
	@Transient
	private Long codPersona;

	public Usuario() {
	}

	public Usuario(Long codigo, String cambioClave, String actualizacionDatos, String estado) {
		this.codigo = codigo;
		this.cambioClave = cambioClave;
		this.actualizacionDatos = actualizacionDatos;
		this.estado = estado;
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public String getCambioClave() {
		return this.cambioClave;
	}

	public void setCambioClave(String cambioClave) {
		this.cambioClave = cambioClave;
	}

	public String getActualizacionDatos() {
		return this.actualizacionDatos;
	}

	public void setActualizacionDatos(String actualizacionDatos) {
		this.actualizacionDatos = actualizacionDatos;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getTokenCambioClave() {
		return tokenCambioClave;
	}

	public void setTokenCambioClave(String tokenCambioClave) {
		this.tokenCambioClave = tokenCambioClave;
	}

	public Date getFechaSolicitudClave() {
		return fechaSolicitudClave;
	}

	public void setFechaSolicitudClave(Date fechaSolicitudClave) {
		this.fechaSolicitudClave = fechaSolicitudClave;
	}

	public Sede getSede() {
		return sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

	public EnumRolSeguridad getEnumRolSeguridad() {
		return enumRolSeguridad;
	}

	public void setEnumRolSeguridad(EnumRolSeguridad enumRolSeguridad) {
		this.enumRolSeguridad = enumRolSeguridad;
	}

	public String getTipoUsuario() {
		if (this.enumRolSeguridad != null) {
			switch (this.enumRolSeguridad) {
			case ADMINISTRADOR_APLICACION:
				tipoUsuario = "Administrador de aplicaciones";
				setEsAdminAplicacion(true);
				break;
			case ADMINISTRADOR_GENERAL:
				tipoUsuario = "Administrador general";
				setEsSuperAdministrador(true);
				break;
			case ADMINISTRADOR_OPERATIVO:
				setEsAdminOperativo(true);
				tipoUsuario = "Administrador operativo";
				break;
			}
		} else {
			tipoUsuario = "Operativo";
		}
		return tipoUsuario;
	}

	public void setTipoUsuario(String tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	public boolean isEsSuperAdministrador() {
		return esSuperAdministrador;
	}

	public void setEsSuperAdministrador(boolean esSuperAdministrador) {
		this.esSuperAdministrador = esSuperAdministrador;
	}

	public String getClaveGenerada() {
		return claveGenerada;
	}

	public void setClaveGenerada(String claveGenerada) {
		this.claveGenerada = claveGenerada;
	}

	public boolean isEsAdminAplicacion() {
		return esAdminAplicacion;
	}

	public void setEsAdminAplicacion(boolean esAdminAplicacion) {
		this.esAdminAplicacion = esAdminAplicacion;
	}

	public boolean isEsAdminOperativo() {
		return esAdminOperativo;
	}

	public void setEsAdminOperativo(boolean esAdminOperativo) {
		this.esAdminOperativo = esAdminOperativo;
	}

	public Boolean getConAsignacion() {
		return conAsignacion;
	}

	public void setConAsignacion(Boolean conAsignacion) {
		this.conAsignacion = conAsignacion;
	}

	public String getSolicitado() {
		return solicitado;
	}

	public void setSolicitado(String solicitado) {
		this.solicitado = solicitado;
	}

	public String getTipoCreacionUsuario() {
		return tipoCreacionUsuario;
	}

	public void setTipoCreacionUsuario(String tipoCreacionUsuario) {
		this.tipoCreacionUsuario = tipoCreacionUsuario;
	}

	public boolean isEsAsignacionOperativo() {
		return esAsignacionOperativo;
	}

	public void setEsAsignacionOperativo(boolean esAsignacionOperativo) {
		this.esAsignacionOperativo = esAsignacionOperativo;
	}

	public String getEstInactivarRoles() {
		return estInactivarRoles;
	}

	public void setEstInactivarRoles(String estInactivarRoles) {
		this.estInactivarRoles = estInactivarRoles;
	}

	public String getEstActivarRoles() {
		return estActivarRoles;
	}

	public void setEstActivarRoles(String estActivarRoles) {
		this.estActivarRoles = estActivarRoles;
	}

	public Long getCodSede() {
		if (this.sede != null) {
			codSede = this.sede.getCodigo();
		}
		return codSede;
	}

	public void setCodSede(Long codSede) {
		this.codSede = codSede;
	}

	public Long getCodPersona() {
		if (this.persona != null) {
			codPersona = this.persona.getCodigo();
		}
		return codPersona;
	}

	public void setCodPersona(Long codPersona) {
		this.codPersona = codPersona;
	}

	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	
	
}
